#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun May 03 05:22:42 CDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=
enableShaders=true
