StartupEvents.registry('block', event => {
    event.create('durable_desh_casing')
        .textureAll('kubejs:block/casing/durable_desh_casing')
        .hardness(2)
        .resistance(3)
        .lightLevel(0)
        .soundType('metal')
        .requiresTool(true)
        .tagBlock('mineable/wrench')

    event.create('firm_ultimet_casing')
        .textureAll('kubejs:block/casing/firm_ultimet_casing')
        .hardness(2)
        .resistance(3)
        .lightLevel(0)
        .soundType('metal')
        .requiresTool(true)
        .tagBlock('mineable/wrench')

    event.create('stout_titanium_carbide_casing')
        .textureAll('kubejs:block/casing/stout_titanium_carbide_casing')
        .hardness(2)
        .resistance(3)
        .lightLevel(0)
        .soundType('metal')
        .requiresTool(true)
        .tagBlock('mineable/wrench')
})